### ISSUE TITLE
A "Getting Started Guide" would be nice :)

### ISSUE THREAD

**Issue by franz-see** [smartanthill/smartanthill1_0#1]

**Comment by ivankravets** [comment]
1. Thanks a lot for the first issue here :+1:  
2. I created new [Milestone 0.1.0](https://github.com/ivankravets/smartanthill/issues?milestone=1&state=open) and you can estimate when it will be released
3. Which type of platforms(boards, MCUs...) do you have?

**Comment by franz-see** [comment]
I don't have any right now. But I used to play with M68HC11 (and one Pico Controller which I don't remember anymore). about 15 yrs ago and I do miss it. But if you're getting started can recommend a good starting device to play with, that would be great :)

**Comment by ivankravets** [comment]
> But if you're getting started can recommend a good starting device to play with, that would be great :)

First of all, you should describe me how do you want to interact with you device. Wired or Wireless? It should be STRICT Embedded board (like [TI Launchpads](http://www.ti.com/ww/en/launchpad/launchpad.html?DCMP=TIMDC_in&HQS=TIMDC-launchpad)) or mini-computer (like [BeagleBone Black](https://www.adafruit.com/products/1876) or [Raspberry Pi](http://www.raspberrypi.org) ) ? 

Secondly, don't forget that you can extend your low-cost MCU board (Arduino-based and etc) with different RF chips (please google on eBay these: RFM69W or nRF24L01).

Lastly, I prefer TI. I don't know why? Maybe I love it :) TI makes crazy dev-boards with excellent peripherals for several $ :) If you interested in:
- **Wireless** - try new [CC3200 SimpleLink Wi-Fi LaunchPad](http://www.ti.com/ww/en/launchpad/launchpads-connected-cc3200-launchxl.html#tabs) 
- **Ethernet** [Tiva C Series Connected LaunchPad](http://www.ti.com/ww/en/launchpad/launchpads-connected-ek-tm4c1294xl.html#tabs)
- **Wired** [Tiva C Series TM4C123G LaunchPad](http://www.ti.com/ww/en/launchpad/launchpads-connected-ek-tm4c123gxl.html#tabs) - it has 2 Controller Area Network (CAN) modules, using CAN protocol version 2.0 part A/B and with bit rates up to 1 Mbps

P.S: I like **Wired** way :) Because I have [CAN bus](http://docs.smartanthill.ikravets.com/en/latest/specification/network/can.html) with several CAN-based MCUs in my home :) But I'm not sure that this is a good idea to start from the _CAN_.

**Comment by ivankravets** [comment]
Done! http://docs.smartanthill.org/en/latest/
